---
title: "animation_lolipops"
author: "Choy Yu Min Justin"
date: "4/11/2020"
output: html_document
---

Import packages
```{r}
packages = c('ggplot2','dplyr','readr', 'gganimate','scales', 'lubridate','animation','stringr','gapminder','png','gifski')

for (p in packages){
  if(!require(p, character.only = T)){
    install.packages(p)
  }
  library(p,character.only = T)
}

```

LoadData
```{r}
```


```{r}
population_data_10_19 <- read_csv("../Data/Residential_Planning/respopagesextod2011to2019.csv")

Population_by_PA <- population_data_10_19 %>%
  group_by(Time,PA, AG)%>%
  summarise(Pop_total = sum(Pop)) %>%
  filter(AG == "0_to_4")

Population_by_PA$Year <- year(mdy(Population_by_PA$Time))

Population_by_PA
```

```{r}

library(gganimate)

p<- ggplot(Population_by_PA,
       aes(x = reorder(PA, Pop_total), y = Pop_total, color = PA)) +
  geom_point(stat = 'identity', size = 5) +
  geom_segment(aes(
    y=100,
    x = PA,
    yend = Pop_total,
    xend = PA)
  )+
  coord_flip() 
```


```{r}
z<- p +transition_states(Year,transition_length = 1,state_length = 2)+transition_time(Year)+labs(title = "Year: {as.integer(frame_time)}") +
  theme(legend.position = "none") + ease_aes("linear")+ shadow_mark(alpha = 0.3, size = 0.5)


animate(z)
```
```{r}

```


